
<h3>Data set #7:<br>
Average earnings (monthly (2015))<br>
http://osp.stat.gov.lt/en/statistiniu-rodikliu-analize?portletFormName=visualization&hash=331ea045-2544-49a2-a495-a99b6758413b</h3>

In [1]:
import csv
filename='Source_datasets/Exported matrix table_d7.csv'
with open(filename, 'r') as f:
    data = list(csv.reader(f))
#print (data)
#print (f)
for row_num in range(0,len(data)):
    print (data[row_num])

['\ufeff', '', '', 'Average earnings | monthly | EUR']
['Net', 'Republic of Lithuania', '2015', '553.9']
['', 'Alytus county', '2015', '476.5']
['', 'Alytus t. mun.', '2015', '503.4']
['', 'Alytus d. mun.', '2015', '460.3']
['', 'Druskininkai mun.', '2015', '452.3']
['', 'Lazdijai d. mun.', '2015', '437.7']
['', 'Varėna d. mun.', '2015', '438.8']
['', 'Kaunas county', '2015', '539.4']
['', 'Birštonas mun.', '2015', '449.2']
['', 'Jonava d. mun.', '2015', '561.4']
['', 'Kaišiadorys d. mun.', '2015', '485.2']
['', 'Kaunas c. mun.', '2015', '553.7']
['', 'Kaunas d. mun.', '2015', '499.4']
['', 'Kėdainiai d. mun.', '2015', '563.0']
['', 'Prienai d. mun.', '2015', '433.1']
['', 'Raseiniai d. mun.', '2015', '437.3']
['', 'Klaipėda county', '2015', '539.8']
['', 'Klaipėda c. mun.', '2015', '586.5']
['', 'Klaipėda d. mun.', '2015', '503.5']
['', 'Kretinga d. mun.', '2015', '430.8']
['', 'Neringa mun.', '2015', '447.7']
['', 'Palanga t. mun.', '2015', '428.3']
['', 'Skuodas d. mun.', '2015', '435.2']
['', 'Šilutė d. mun.', '2015', '448.0']
['', 'Marijampolė county', '2015', '461.7']
['', 'Kalvarija mun.', '2015', '411.5']
['', 'Kazlų Rūda mun.', '2015', '519.7']
['', 'Marijampolė mun.', '2015', '474.9']
['', 'Marijampolė d. mun.', '2015', '']
['', 'Šakiai d. mun.', '2015', '441.4']
['', 'Vilkaviškis d. mun.', '2015', '425.7']
['', 'Panevėžys county', '2015', '487.2']
['', 'Biržai d. mun.', '2015', '446.3']
['', 'Kupiškis d. mun.', '2015', '428.9']
['', 'Panevėžys c. mun.', '2015', '523.8']
['', 'Panevėžys d. mun.', '2015', '427.1']
['', 'Pasvalys d. mun.', '2015', '446.8']
['', 'Rokiškis d. mun.', '2015', '463.0']
['', 'Šiauliai county', '2015', '469.3']
['', 'Akmenė d. mun.', '2015', '506.7']
['', 'Joniškis d. mun.', '2015', '451.4']
['', 'Kelmė d. mun.', '2015', '428.8']
['', 'Pakruojis d. mun.', '2015', '457.3']
['', 'Radviliškis d. mun.', '2015', '415.5']
['', 'Šiauliai c. mun.', '2015', '486.5']
['', 'Šiauliai d. mun.', '2015', '438.6']
['', 'Tauragė county', '2015', '448.4']
['', 'Jurbarkas d. mun.', '2015', '433.1']
['', 'Pagėgiai mun.', '2015', '496.8']
['', 'Šilalė d. mun.', '2015', '437.6']
['', 'Tauragė d. mun.', '2015', '450.5']
['', 'Telšiai county', '2015', '497.3']
['', 'Mažeikiai d. mun.', '2015', '536.1']
['', 'Plungė d. mun.', '2015', '450.1']
['', 'Rietavas mun.', '2015', '483.8']
['', 'Telšiai d. mun.', '2015', '481.2']
['', 'Utena county', '2015', '482.6']
['', 'Anykščiai d. mun.', '2015', '443.0']
['', 'Ignalina d. mun.', '2015', '437.8']
['', 'Molėtai d. mun.', '2015', '428.6']
['', 'Utena d. mun.', '2015', '476.3']
['', 'Visaginas mun.', '2015', '588.3']
['', 'Zarasai d. mun.', '2015', '411.3']
['', 'Vilnius county', '2015', '618.5']
['', 'Elektrėnai mun.', '2015', '543.9']
['', 'Šalčininkai d. mun.', '2015', '398.5']
['', 'Širvintos d. mun.', '2015', '426.6']
['', 'Švenčionys d. mun.', '2015', '456.5']
['', 'Trakai d. mun.', '2015', '504.7']
['', 'Ukmergė d. mun.', '2015', '458.0']
['', 'Vilnius c. mun.', '2015', '639.2']
['', 'Vilnius d. mun.', '2015', '509.7']

In [3]:
#remove aggregated rows, as aggregation will take place later e.g. in pivotjs
keysList=['Republic','county']
tobedeletedList=[]
typeCurser={}#to tag age layers 
updated_lengh=len(data)
for row_num in range(0,updated_lengh):
    for key in keysList:
        #print (key)
        if key in data[row_num][1]:
            tobedeletedList.append(row_num)#for males row
            #tobedeletedList.append(row_num+1)#for the females row
            if 'Republic' in key:
                typeCurser[data[row_num][0]]=row_num
                
import operator

sorted_typeCurser = sorted(typeCurser.items(), key=operator.itemgetter(1))

print (tobedeletedList)
print (typeCurser)
print('sorted cursor:{}'.format(sorted_typeCurser))


for aggregated_row_num in tobedeletedList:
    #print (data[aggregated_row_num])
    data[aggregated_row_num]=['']
    #tobedeletedList[:] = [x - 1 for x in tobedeletedList]
   #print (tobedeletedList)
    
for row_num in range(0,len(data)):
    print (data[row_num])

[1, 2, 8, 17, 25, 32, 39, 47, 52, 57, 64]
{'Net': 1}
sorted cursor:[('Net', 1)]
['\ufeff', '', '', 'Average earnings | monthly | EUR']
['']
['']
['', 'Alytus t. mun.', '2015', '503.4']
['', 'Alytus d. mun.', '2015', '460.3']
['', 'Druskininkai mun.', '2015', '452.3']
['', 'Lazdijai d. mun.', '2015', '437.7']
['', 'Varėna d. mun.', '2015', '438.8']
['']
['', 'Birštonas mun.', '2015', '449.2']
['', 'Jonava d. mun.', '2015', '561.4']
['', 'Kaišiadorys d. mun.', '2015', '485.2']
['', 'Kaunas c. mun.', '2015', '553.7']
['', 'Kaunas d. mun.', '2015', '499.4']
['', 'Kėdainiai d. mun.', '2015', '563.0']
['', 'Prienai d. mun.', '2015', '433.1']
['', 'Raseiniai d. mun.', '2015', '437.3']
['']
['', 'Klaipėda c. mun.', '2015', '586.5']
['', 'Klaipėda d. mun.', '2015', '503.5']
['', 'Kretinga d. mun.', '2015', '430.8']
['', 'Neringa mun.', '2015', '447.7']
['', 'Palanga t. mun.', '2015', '428.3']
['', 'Skuodas d. mun.', '2015', '435.2']
['', 'Šilutė d. mun.', '2015', '448.0']
['']
['', 'Kalvarija mun.', '2015', '411.5']
['', 'Kazlų Rūda mun.', '2015', '519.7']
['', 'Marijampolė mun.', '2015', '474.9']
['', 'Marijampolė d. mun.', '2015', '']
['', 'Šakiai d. mun.', '2015', '441.4']
['', 'Vilkaviškis d. mun.', '2015', '425.7']
['']
['', 'Biržai d. mun.', '2015', '446.3']
['', 'Kupiškis d. mun.', '2015', '428.9']
['', 'Panevėžys c. mun.', '2015', '523.8']
['', 'Panevėžys d. mun.', '2015', '427.1']
['', 'Pasvalys d. mun.', '2015', '446.8']
['', 'Rokiškis d. mun.', '2015', '463.0']
['']
['', 'Akmenė d. mun.', '2015', '506.7']
['', 'Joniškis d. mun.', '2015', '451.4']
['', 'Kelmė d. mun.', '2015', '428.8']
['', 'Pakruojis d. mun.', '2015', '457.3']
['', 'Radviliškis d. mun.', '2015', '415.5']
['', 'Šiauliai c. mun.', '2015', '486.5']
['', 'Šiauliai d. mun.', '2015', '438.6']
['']
['', 'Jurbarkas d. mun.', '2015', '433.1']
['', 'Pagėgiai mun.', '2015', '496.8']
['', 'Šilalė d. mun.', '2015', '437.6']
['', 'Tauragė d. mun.', '2015', '450.5']
['']
['', 'Mažeikiai d. mun.', '2015', '536.1']
['', 'Plungė d. mun.', '2015', '450.1']
['', 'Rietavas mun.', '2015', '483.8']
['', 'Telšiai d. mun.', '2015', '481.2']
['']
['', 'Anykščiai d. mun.', '2015', '443.0']
['', 'Ignalina d. mun.', '2015', '437.8']
['', 'Molėtai d. mun.', '2015', '428.6']
['', 'Utena d. mun.', '2015', '476.3']
['', 'Visaginas mun.', '2015', '588.3']
['', 'Zarasai d. mun.', '2015', '411.3']
['']
['', 'Elektrėnai mun.', '2015', '543.9']
['', 'Šalčininkai d. mun.', '2015', '398.5']
['', 'Širvintos d. mun.', '2015', '426.6']
['', 'Švenčionys d. mun.', '2015', '456.5']
['', 'Trakai d. mun.', '2015', '504.7']
['', 'Ukmergė d. mun.', '2015', '458.0']
['', 'Vilnius c. mun.', '2015', '639.2']
['', 'Vilnius d. mun.', '2015', '509.7']

In [6]:
#add missing Age tag layers values
firstTypeLayer_curser=[sorted_typeCurser[0][1],len(data)]
firstTypeLayer_tag=sorted_typeCurser[0][0]


print(firstTypeLayer_curser)

for i in range(firstTypeLayer_curser[0],firstTypeLayer_curser[1]):
    data[i][0]=firstTypeLayer_tag

for row_num in range(0,len(data)):
    print (data[row_num])

[1, 73]
['\ufeff', '', '', 'Average earnings | monthly | EUR']
['Net']
['Net']
['Net', 'Alytus t. mun.', '2015', '503.4']
['Net', 'Alytus d. mun.', '2015', '460.3']
['Net', 'Druskininkai mun.', '2015', '452.3']
['Net', 'Lazdijai d. mun.', '2015', '437.7']
['Net', 'Varėna d. mun.', '2015', '438.8']
['Net']
['Net', 'Birštonas mun.', '2015', '449.2']
['Net', 'Jonava d. mun.', '2015', '561.4']
['Net', 'Kaišiadorys d. mun.', '2015', '485.2']
['Net', 'Kaunas c. mun.', '2015', '553.7']
['Net', 'Kaunas d. mun.', '2015', '499.4']
['Net', 'Kėdainiai d. mun.', '2015', '563.0']
['Net', 'Prienai d. mun.', '2015', '433.1']
['Net', 'Raseiniai d. mun.', '2015', '437.3']
['Net']
['Net', 'Klaipėda c. mun.', '2015', '586.5']
['Net', 'Klaipėda d. mun.', '2015', '503.5']
['Net', 'Kretinga d. mun.', '2015', '430.8']
['Net', 'Neringa mun.', '2015', '447.7']
['Net', 'Palanga t. mun.', '2015', '428.3']
['Net', 'Skuodas d. mun.', '2015', '435.2']
['Net', 'Šilutė d. mun.', '2015', '448.0']
['Net']
['Net', 'Kalvarija mun.', '2015', '411.5']
['Net', 'Kazlų Rūda mun.', '2015', '519.7']
['Net', 'Marijampolė mun.', '2015', '474.9']
['Net', 'Marijampolė d. mun.', '2015', '']
['Net', 'Šakiai d. mun.', '2015', '441.4']
['Net', 'Vilkaviškis d. mun.', '2015', '425.7']
['Net']
['Net', 'Biržai d. mun.', '2015', '446.3']
['Net', 'Kupiškis d. mun.', '2015', '428.9']
['Net', 'Panevėžys c. mun.', '2015', '523.8']
['Net', 'Panevėžys d. mun.', '2015', '427.1']
['Net', 'Pasvalys d. mun.', '2015', '446.8']
['Net', 'Rokiškis d. mun.', '2015', '463.0']
['Net']
['Net', 'Akmenė d. mun.', '2015', '506.7']
['Net', 'Joniškis d. mun.', '2015', '451.4']
['Net', 'Kelmė d. mun.', '2015', '428.8']
['Net', 'Pakruojis d. mun.', '2015', '457.3']
['Net', 'Radviliškis d. mun.', '2015', '415.5']
['Net', 'Šiauliai c. mun.', '2015', '486.5']
['Net', 'Šiauliai d. mun.', '2015', '438.6']
['Net']
['Net', 'Jurbarkas d. mun.', '2015', '433.1']
['Net', 'Pagėgiai mun.', '2015', '496.8']
['Net', 'Šilalė d. mun.', '2015', '437.6']
['Net', 'Tauragė d. mun.', '2015', '450.5']
['Net']
['Net', 'Mažeikiai d. mun.', '2015', '536.1']
['Net', 'Plungė d. mun.', '2015', '450.1']
['Net', 'Rietavas mun.', '2015', '483.8']
['Net', 'Telšiai d. mun.', '2015', '481.2']
['Net']
['Net', 'Anykščiai d. mun.', '2015', '443.0']
['Net', 'Ignalina d. mun.', '2015', '437.8']
['Net', 'Molėtai d. mun.', '2015', '428.6']
['Net', 'Utena d. mun.', '2015', '476.3']
['Net', 'Visaginas mun.', '2015', '588.3']
['Net', 'Zarasai d. mun.', '2015', '411.3']
['Net']
['Net', 'Elektrėnai mun.', '2015', '543.9']
['Net', 'Šalčininkai d. mun.', '2015', '398.5']
['Net', 'Širvintos d. mun.', '2015', '426.6']
['Net', 'Švenčionys d. mun.', '2015', '456.5']
['Net', 'Trakai d. mun.', '2015', '504.7']
['Net', 'Ukmergė d. mun.', '2015', '458.0']
['Net', 'Vilnius c. mun.', '2015', '639.2']
['Net', 'Vilnius d. mun.', '2015', '509.7']

In [7]:
#permanent clean of unwanted rows in dataset
tobedeletedList=[]
for row_num in range (1,len(data)):
    if (len(data[row_num])<3):#regarding temporary header size
        #print ("row num{}:{}".format(i,data[row_num]))
        tobedeletedList.append(row_num)
print (tobedeletedList)
for aggregated_row_num in tobedeletedList:
    #print (data[aggregated_row_num])
    del data[aggregated_row_num]
    tobedeletedList[:] = [x - 1 for x in tobedeletedList]
   #print (tobedeletedList)
    
for row_num in range(0,len(data)):
    print (data[row_num])

[1, 2, 8, 17, 25, 32, 39, 47, 52, 57, 64]
['\ufeff', '', '', 'Average earnings | monthly | EUR']
['Net', 'Alytus t. mun.', '2015', '503.4']
['Net', 'Alytus d. mun.', '2015', '460.3']
['Net', 'Druskininkai mun.', '2015', '452.3']
['Net', 'Lazdijai d. mun.', '2015', '437.7']
['Net', 'Varėna d. mun.', '2015', '438.8']
['Net', 'Birštonas mun.', '2015', '449.2']
['Net', 'Jonava d. mun.', '2015', '561.4']
['Net', 'Kaišiadorys d. mun.', '2015', '485.2']
['Net', 'Kaunas c. mun.', '2015', '553.7']
['Net', 'Kaunas d. mun.', '2015', '499.4']
['Net', 'Kėdainiai d. mun.', '2015', '563.0']
['Net', 'Prienai d. mun.', '2015', '433.1']
['Net', 'Raseiniai d. mun.', '2015', '437.3']
['Net', 'Klaipėda c. mun.', '2015', '586.5']
['Net', 'Klaipėda d. mun.', '2015', '503.5']
['Net', 'Kretinga d. mun.', '2015', '430.8']
['Net', 'Neringa mun.', '2015', '447.7']
['Net', 'Palanga t. mun.', '2015', '428.3']
['Net', 'Skuodas d. mun.', '2015', '435.2']
['Net', 'Šilutė d. mun.', '2015', '448.0']
['Net', 'Kalvarija mun.', '2015', '411.5']
['Net', 'Kazlų Rūda mun.', '2015', '519.7']
['Net', 'Marijampolė mun.', '2015', '474.9']
['Net', 'Marijampolė d. mun.', '2015', '']
['Net', 'Šakiai d. mun.', '2015', '441.4']
['Net', 'Vilkaviškis d. mun.', '2015', '425.7']
['Net', 'Biržai d. mun.', '2015', '446.3']
['Net', 'Kupiškis d. mun.', '2015', '428.9']
['Net', 'Panevėžys c. mun.', '2015', '523.8']
['Net', 'Panevėžys d. mun.', '2015', '427.1']
['Net', 'Pasvalys d. mun.', '2015', '446.8']
['Net', 'Rokiškis d. mun.', '2015', '463.0']
['Net', 'Akmenė d. mun.', '2015', '506.7']
['Net', 'Joniškis d. mun.', '2015', '451.4']
['Net', 'Kelmė d. mun.', '2015', '428.8']
['Net', 'Pakruojis d. mun.', '2015', '457.3']
['Net', 'Radviliškis d. mun.', '2015', '415.5']
['Net', 'Šiauliai c. mun.', '2015', '486.5']
['Net', 'Šiauliai d. mun.', '2015', '438.6']
['Net', 'Jurbarkas d. mun.', '2015', '433.1']
['Net', 'Pagėgiai mun.', '2015', '496.8']
['Net', 'Šilalė d. mun.', '2015', '437.6']
['Net', 'Tauragė d. mun.', '2015', '450.5']
['Net', 'Mažeikiai d. mun.', '2015', '536.1']
['Net', 'Plungė d. mun.', '2015', '450.1']
['Net', 'Rietavas mun.', '2015', '483.8']
['Net', 'Telšiai d. mun.', '2015', '481.2']
['Net', 'Anykščiai d. mun.', '2015', '443.0']
['Net', 'Ignalina d. mun.', '2015', '437.8']
['Net', 'Molėtai d. mun.', '2015', '428.6']
['Net', 'Utena d. mun.', '2015', '476.3']
['Net', 'Visaginas mun.', '2015', '588.3']
['Net', 'Zarasai d. mun.', '2015', '411.3']
['Net', 'Elektrėnai mun.', '2015', '543.9']
['Net', 'Šalčininkai d. mun.', '2015', '398.5']
['Net', 'Širvintos d. mun.', '2015', '426.6']
['Net', 'Švenčionys d. mun.', '2015', '456.5']
['Net', 'Trakai d. mun.', '2015', '504.7']
['Net', 'Ukmergė d. mun.', '2015', '458.0']
['Net', 'Vilnius c. mun.', '2015', '639.2']
['Net', 'Vilnius d. mun.', '2015', '509.7']

In [8]:
#add missing country values
for row_num in range(1,len(data)):
    data[row_num].append('Republic of Lithuania')
for row_num in range(0,len(data)):
    print (data[row_num])

['\ufeff', '', '', 'Average earnings | monthly | EUR']
['Net', 'Alytus t. mun.', '2015', '503.4', 'Republic of Lithuania']
['Net', 'Alytus d. mun.', '2015', '460.3', 'Republic of Lithuania']
['Net', 'Druskininkai mun.', '2015', '452.3', 'Republic of Lithuania']
['Net', 'Lazdijai d. mun.', '2015', '437.7', 'Republic of Lithuania']
['Net', 'Varėna d. mun.', '2015', '438.8', 'Republic of Lithuania']
['Net', 'Birštonas mun.', '2015', '449.2', 'Republic of Lithuania']
['Net', 'Jonava d. mun.', '2015', '561.4', 'Republic of Lithuania']
['Net', 'Kaišiadorys d. mun.', '2015', '485.2', 'Republic of Lithuania']
['Net', 'Kaunas c. mun.', '2015', '553.7', 'Republic of Lithuania']
['Net', 'Kaunas d. mun.', '2015', '499.4', 'Republic of Lithuania']
['Net', 'Kėdainiai d. mun.', '2015', '563.0', 'Republic of Lithuania']
['Net', 'Prienai d. mun.', '2015', '433.1', 'Republic of Lithuania']
['Net', 'Raseiniai d. mun.', '2015', '437.3', 'Republic of Lithuania']
['Net', 'Klaipėda c. mun.', '2015', '586.5', 'Republic of Lithuania']
['Net', 'Klaipėda d. mun.', '2015', '503.5', 'Republic of Lithuania']
['Net', 'Kretinga d. mun.', '2015', '430.8', 'Republic of Lithuania']
['Net', 'Neringa mun.', '2015', '447.7', 'Republic of Lithuania']
['Net', 'Palanga t. mun.', '2015', '428.3', 'Republic of Lithuania']
['Net', 'Skuodas d. mun.', '2015', '435.2', 'Republic of Lithuania']
['Net', 'Šilutė d. mun.', '2015', '448.0', 'Republic of Lithuania']
['Net', 'Kalvarija mun.', '2015', '411.5', 'Republic of Lithuania']
['Net', 'Kazlų Rūda mun.', '2015', '519.7', 'Republic of Lithuania']
['Net', 'Marijampolė mun.', '2015', '474.9', 'Republic of Lithuania']
['Net', 'Marijampolė d. mun.', '2015', '', 'Republic of Lithuania']
['Net', 'Šakiai d. mun.', '2015', '441.4', 'Republic of Lithuania']
['Net', 'Vilkaviškis d. mun.', '2015', '425.7', 'Republic of Lithuania']
['Net', 'Biržai d. mun.', '2015', '446.3', 'Republic of Lithuania']
['Net', 'Kupiškis d. mun.', '2015', '428.9', 'Republic of Lithuania']
['Net', 'Panevėžys c. mun.', '2015', '523.8', 'Republic of Lithuania']
['Net', 'Panevėžys d. mun.', '2015', '427.1', 'Republic of Lithuania']
['Net', 'Pasvalys d. mun.', '2015', '446.8', 'Republic of Lithuania']
['Net', 'Rokiškis d. mun.', '2015', '463.0', 'Republic of Lithuania']
['Net', 'Akmenė d. mun.', '2015', '506.7', 'Republic of Lithuania']
['Net', 'Joniškis d. mun.', '2015', '451.4', 'Republic of Lithuania']
['Net', 'Kelmė d. mun.', '2015', '428.8', 'Republic of Lithuania']
['Net', 'Pakruojis d. mun.', '2015', '457.3', 'Republic of Lithuania']
['Net', 'Radviliškis d. mun.', '2015', '415.5', 'Republic of Lithuania']
['Net', 'Šiauliai c. mun.', '2015', '486.5', 'Republic of Lithuania']
['Net', 'Šiauliai d. mun.', '2015', '438.6', 'Republic of Lithuania']
['Net', 'Jurbarkas d. mun.', '2015', '433.1', 'Republic of Lithuania']
['Net', 'Pagėgiai mun.', '2015', '496.8', 'Republic of Lithuania']
['Net', 'Šilalė d. mun.', '2015', '437.6', 'Republic of Lithuania']
['Net', 'Tauragė d. mun.', '2015', '450.5', 'Republic of Lithuania']
['Net', 'Mažeikiai d. mun.', '2015', '536.1', 'Republic of Lithuania']
['Net', 'Plungė d. mun.', '2015', '450.1', 'Republic of Lithuania']
['Net', 'Rietavas mun.', '2015', '483.8', 'Republic of Lithuania']
['Net', 'Telšiai d. mun.', '2015', '481.2', 'Republic of Lithuania']
['Net', 'Anykščiai d. mun.', '2015', '443.0', 'Republic of Lithuania']
['Net', 'Ignalina d. mun.', '2015', '437.8', 'Republic of Lithuania']
['Net', 'Molėtai d. mun.', '2015', '428.6', 'Republic of Lithuania']
['Net', 'Utena d. mun.', '2015', '476.3', 'Republic of Lithuania']
['Net', 'Visaginas mun.', '2015', '588.3', 'Republic of Lithuania']
['Net', 'Zarasai d. mun.', '2015', '411.3', 'Republic of Lithuania']
['Net', 'Elektrėnai mun.', '2015', '543.9', 'Republic of Lithuania']
['Net', 'Šalčininkai d. mun.', '2015', '398.5', 'Republic of Lithuania']
['Net', 'Širvintos d. mun.', '2015', '426.6', 'Republic of Lithuania']
['Net', 'Švenčionys d. mun.', '2015', '456.5', 'Republic of Lithuania']
['Net', 'Trakai d. mun.', '2015', '504.7', 'Republic of Lithuania']
['Net', 'Ukmergė d. mun.', '2015', '458.0', 'Republic of Lithuania']
['Net', 'Vilnius c. mun.', '2015', '639.2', 'Republic of Lithuania']
['Net', 'Vilnius d. mun.', '2015', '509.7', 'Republic of Lithuania']

In [9]:
#add missing county values
for row_num in range(1,6):
        data[row_num].append('Alytus county')
for row_num in range(6,14):
        data[row_num].append('Kaunas county')
for row_num in range(14,21):
        data[row_num].append('Klaipeda county')
for row_num in range(21,27):
        data[row_num].append('Marijampole county')
for row_num in range(27,33):
        data[row_num].append('Panevezys county')
for row_num in range(33,40):
        data[row_num].append('Siauliai county')
for row_num in range(40,44):
        data[row_num].append('Taurage county')
for row_num in range(44,48):
        data[row_num].append('Telsiai county')
for row_num in range(48,54):
        data[row_num].append('Utena county')
for row_num in range(54,62):
        data[row_num].append('Vilnius county')

        
for row_num in range(0,len(data)):
    print (data[row_num])

['\ufeff', '', '', 'Average earnings | monthly | EUR']
['Net', 'Alytus t. mun.', '2015', '503.4', 'Republic of Lithuania', 'Alytus county']
['Net', 'Alytus d. mun.', '2015', '460.3', 'Republic of Lithuania', 'Alytus county']
['Net', 'Druskininkai mun.', '2015', '452.3', 'Republic of Lithuania', 'Alytus county']
['Net', 'Lazdijai d. mun.', '2015', '437.7', 'Republic of Lithuania', 'Alytus county']
['Net', 'Varėna d. mun.', '2015', '438.8', 'Republic of Lithuania', 'Alytus county']
['Net', 'Birštonas mun.', '2015', '449.2', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Jonava d. mun.', '2015', '561.4', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Kaišiadorys d. mun.', '2015', '485.2', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Kaunas c. mun.', '2015', '553.7', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Kaunas d. mun.', '2015', '499.4', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Kėdainiai d. mun.', '2015', '563.0', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Prienai d. mun.', '2015', '433.1', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Raseiniai d. mun.', '2015', '437.3', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Klaipėda c. mun.', '2015', '586.5', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Klaipėda d. mun.', '2015', '503.5', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Kretinga d. mun.', '2015', '430.8', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Neringa mun.', '2015', '447.7', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Palanga t. mun.', '2015', '428.3', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Skuodas d. mun.', '2015', '435.2', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Šilutė d. mun.', '2015', '448.0', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Kalvarija mun.', '2015', '411.5', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Kazlų Rūda mun.', '2015', '519.7', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Marijampolė mun.', '2015', '474.9', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Marijampolė d. mun.', '2015', '', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Šakiai d. mun.', '2015', '441.4', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Vilkaviškis d. mun.', '2015', '425.7', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Biržai d. mun.', '2015', '446.3', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Kupiškis d. mun.', '2015', '428.9', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Panevėžys c. mun.', '2015', '523.8', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Panevėžys d. mun.', '2015', '427.1', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Pasvalys d. mun.', '2015', '446.8', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Rokiškis d. mun.', '2015', '463.0', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Akmenė d. mun.', '2015', '506.7', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Joniškis d. mun.', '2015', '451.4', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Kelmė d. mun.', '2015', '428.8', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Pakruojis d. mun.', '2015', '457.3', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Radviliškis d. mun.', '2015', '415.5', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Šiauliai c. mun.', '2015', '486.5', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Šiauliai d. mun.', '2015', '438.6', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Jurbarkas d. mun.', '2015', '433.1', 'Republic of Lithuania', 'Taurage county']
['Net', 'Pagėgiai mun.', '2015', '496.8', 'Republic of Lithuania', 'Taurage county']
['Net', 'Šilalė d. mun.', '2015', '437.6', 'Republic of Lithuania', 'Taurage county']
['Net', 'Tauragė d. mun.', '2015', '450.5', 'Republic of Lithuania', 'Taurage county']
['Net', 'Mažeikiai d. mun.', '2015', '536.1', 'Republic of Lithuania', 'Telsiai county']
['Net', 'Plungė d. mun.', '2015', '450.1', 'Republic of Lithuania', 'Telsiai county']
['Net', 'Rietavas mun.', '2015', '483.8', 'Republic of Lithuania', 'Telsiai county']
['Net', 'Telšiai d. mun.', '2015', '481.2', 'Republic of Lithuania', 'Telsiai county']
['Net', 'Anykščiai d. mun.', '2015', '443.0', 'Republic of Lithuania', 'Utena county']
['Net', 'Ignalina d. mun.', '2015', '437.8', 'Republic of Lithuania', 'Utena county']
['Net', 'Molėtai d. mun.', '2015', '428.6', 'Republic of Lithuania', 'Utena county']
['Net', 'Utena d. mun.', '2015', '476.3', 'Republic of Lithuania', 'Utena county']
['Net', 'Visaginas mun.', '2015', '588.3', 'Republic of Lithuania', 'Utena county']
['Net', 'Zarasai d. mun.', '2015', '411.3', 'Republic of Lithuania', 'Utena county']
['Net', 'Elektrėnai mun.', '2015', '543.9', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Šalčininkai d. mun.', '2015', '398.5', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Širvintos d. mun.', '2015', '426.6', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Švenčionys d. mun.', '2015', '456.5', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Trakai d. mun.', '2015', '504.7', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Ukmergė d. mun.', '2015', '458.0', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Vilnius c. mun.', '2015', '639.2', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Vilnius d. mun.', '2015', '509.7', 'Republic of Lithuania', 'Vilnius county']

In [12]:
#Adding collumn headers istead of the melformed header
headerList=['Type','Municipality','Time_period','Average_earnings_monthly_EUR','Country','County']
del data[0]
data.insert( 0, headerList)
for row_num in range(0,len(data)):
    print (data[row_num])

['Type', 'Municipality', 'Time_period', 'Average_earnings_monthly_EUR', 'Country', 'County']
['Net', 'Alytus t. mun.', '2015', '503.4', 'Republic of Lithuania', 'Alytus county']
['Net', 'Alytus d. mun.', '2015', '460.3', 'Republic of Lithuania', 'Alytus county']
['Net', 'Druskininkai mun.', '2015', '452.3', 'Republic of Lithuania', 'Alytus county']
['Net', 'Lazdijai d. mun.', '2015', '437.7', 'Republic of Lithuania', 'Alytus county']
['Net', 'Varėna d. mun.', '2015', '438.8', 'Republic of Lithuania', 'Alytus county']
['Net', 'Birštonas mun.', '2015', '449.2', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Jonava d. mun.', '2015', '561.4', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Kaišiadorys d. mun.', '2015', '485.2', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Kaunas c. mun.', '2015', '553.7', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Kaunas d. mun.', '2015', '499.4', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Kėdainiai d. mun.', '2015', '563.0', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Prienai d. mun.', '2015', '433.1', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Raseiniai d. mun.', '2015', '437.3', 'Republic of Lithuania', 'Kanuas county']
['Net', 'Klaipėda c. mun.', '2015', '586.5', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Klaipėda d. mun.', '2015', '503.5', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Kretinga d. mun.', '2015', '430.8', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Neringa mun.', '2015', '447.7', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Palanga t. mun.', '2015', '428.3', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Skuodas d. mun.', '2015', '435.2', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Šilutė d. mun.', '2015', '448.0', 'Republic of Lithuania', 'Klaipeda county']
['Net', 'Kalvarija mun.', '2015', '411.5', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Kazlų Rūda mun.', '2015', '519.7', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Marijampolė mun.', '2015', '474.9', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Marijampolė d. mun.', '2015', '', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Šakiai d. mun.', '2015', '441.4', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Vilkaviškis d. mun.', '2015', '425.7', 'Republic of Lithuania', 'Marijampole county']
['Net', 'Biržai d. mun.', '2015', '446.3', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Kupiškis d. mun.', '2015', '428.9', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Panevėžys c. mun.', '2015', '523.8', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Panevėžys d. mun.', '2015', '427.1', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Pasvalys d. mun.', '2015', '446.8', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Rokiškis d. mun.', '2015', '463.0', 'Republic of Lithuania', 'Panevezys county']
['Net', 'Akmenė d. mun.', '2015', '506.7', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Joniškis d. mun.', '2015', '451.4', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Kelmė d. mun.', '2015', '428.8', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Pakruojis d. mun.', '2015', '457.3', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Radviliškis d. mun.', '2015', '415.5', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Šiauliai c. mun.', '2015', '486.5', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Šiauliai d. mun.', '2015', '438.6', 'Republic of Lithuania', 'Siauliai county']
['Net', 'Jurbarkas d. mun.', '2015', '433.1', 'Republic of Lithuania', 'Taurage county']
['Net', 'Pagėgiai mun.', '2015', '496.8', 'Republic of Lithuania', 'Taurage county']
['Net', 'Šilalė d. mun.', '2015', '437.6', 'Republic of Lithuania', 'Taurage county']
['Net', 'Tauragė d. mun.', '2015', '450.5', 'Republic of Lithuania', 'Taurage county']
['Net', 'Mažeikiai d. mun.', '2015', '536.1', 'Republic of Lithuania', 'Telsiai county']
['Net', 'Plungė d. mun.', '2015', '450.1', 'Republic of Lithuania', 'Telsiai county']
['Net', 'Rietavas mun.', '2015', '483.8', 'Republic of Lithuania', 'Telsiai county']
['Net', 'Telšiai d. mun.', '2015', '481.2', 'Republic of Lithuania', 'Telsiai county']
['Net', 'Anykščiai d. mun.', '2015', '443.0', 'Republic of Lithuania', 'Utena county']
['Net', 'Ignalina d. mun.', '2015', '437.8', 'Republic of Lithuania', 'Utena county']
['Net', 'Molėtai d. mun.', '2015', '428.6', 'Republic of Lithuania', 'Utena county']
['Net', 'Utena d. mun.', '2015', '476.3', 'Republic of Lithuania', 'Utena county']
['Net', 'Visaginas mun.', '2015', '588.3', 'Republic of Lithuania', 'Utena county']
['Net', 'Zarasai d. mun.', '2015', '411.3', 'Republic of Lithuania', 'Utena county']
['Net', 'Elektrėnai mun.', '2015', '543.9', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Šalčininkai d. mun.', '2015', '398.5', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Širvintos d. mun.', '2015', '426.6', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Švenčionys d. mun.', '2015', '456.5', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Trakai d. mun.', '2015', '504.7', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Ukmergė d. mun.', '2015', '458.0', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Vilnius c. mun.', '2015', '639.2', 'Republic of Lithuania', 'Vilnius county']
['Net', 'Vilnius d. mun.', '2015', '509.7', 'Republic of Lithuania', 'Vilnius county']

In [13]:
import csv
#print (data)
with open("Ready_datasets/readyDataSet7.csv", "w") as f:
    writer = csv.writer(f)
    writer.writerows(data)